### ISSUE TITLE
Build the images on a daily basis

### ISSUE THREAD

**Issue by dvandyk** [eos/docker.io#8]
@mreboud After presenting at the IPPP computing club how we use Docker + Github Actions, in a discussion with Yannick we agreed that building the images on a daily basis would be a good idea. At the same time, we should use a fixed image version in the EOS workflows, to ensure a working state.

**Comment by mreboud** [comment]
I fully agree, but do you plan to store all of these images?

**Comment by dvandyk** [comment]
Fixed image version are used now. Giving up on the daily build.
